Debug build client with tmate

diff --git a/.github/workflows/build-client.yml b/.github/workflows/build-client.yml
--- a/.github/workflows/build-client.yml
+++ b/.github/workflows/build-client.yml
@@ -82,6 +82,9 @@ jobs:
         with:
           python-version: '3.11'
       -
+        name: Setup tmate session (debug)
+        uses: mxschmitt/action-tmate@v3
+      -
         name: Build package
         shell: bash
         run: |
@@ -98,6 +101,9 @@ jobs:
           if [ "${{ matrix.platform }}" = "linux" -a "${{ matrix.arch }}" = "x64" ]; then
             mv -v out/make/AppImage/x64/*.AppImage ../client-build-files/${CLIENT_FILENAME%.*}.AppImage
           fi
+
+          echo 'Failing on purpose'
+          exit 1
       -
         name: Upload build artifact
         uses: actions/upload-artifact@v4
